### ISSUE TITLE
[CI] publish the npm package

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/synthetics#107]
the package should be published as @elastic/synthetics when a new tag is created, a similar process we have to the Agent RUM.

```
Scenario: We want to release a new npm package
  Given a new tag in the GitHub repository
  When GitHub notifies the push event of the tag to Jenkins
  Then a new build is a trigger
  Then an npm package is built for the tag
  Then an approval is requested to publish the npm package
  Then if the package is approved the package is released on npm
```

Optional process for PR/Braches
```
Scenario We push changes to a PR/Branch
  Given push event of the change arrives at Jenkins
  When a build success
  Then an npm SNAPSHOT package is built for the commit
  Then  the SNAPSHOT package is released on SOMEPLACE
```

cc @andrewvc @elastic/observablt-robots

**Comment by andrewvc** [comment]
Are there any actions on our side to move this forward?

**Comment by kuisathaverat** [comment]
find time to make it 😄 , how much rush we have?

**Comment by paulb-elastic** [comment]
Discussed the priority of this within the team. This is a requirement for Synthetics GA, although would also be useful to get in for beta if that’s possible.

**Comment by v1v** [comment]
I'd be working on this, I'd use a similar approach as done with the apm-agent-rumjs project (see https://github.com/elastic/apm-agent-rum-js/pull/602)

Regarding the publishing process:
* Package name -> https://www.npmjs.com/package/@elastic/synthetics
* 2FA authentication.
* Vault secured (using tokens).
* Email/Slack communication regarding a release ready to be pushed and a release already pushed.

I've got some questions:
* what's the email address to notify when a release has been started (failed or released).?
* what's the slack channel to notify the above events?
* changelog is something to be also automated? If so, I'd say let's move this to another follow up
* what's the release/publish command you run to do releases now?

Cheers

**Comment by v1v** [comment]
as we discussed offline, I already got those details. I'll start now with this. Thanks

**Comment by v1v** [comment]
@paulb-elastic and @andrewvc, https://github.com/elastic/synthetics/pull/213 is ready to be merged, I already explained how to use it in the README file and also in the description.

For the very first release I'd like to be involved, though @vigneshshanmugam is already aware of the process since it's similar to the `apm-agent-rum-js` one. When do you plan to do a release? 

OTOH, we can work on the changelog automation if needed. There are different approaches we have automated, for instance the `apm-agent-php` project consumes the GitHub issues/pull requests to generate the `CHANGELOG.asscidoc` that it's consumed by the docs automation (and populated automatically to the elastic.co webpage). Happy to discuss this in a follow up to avoid messing around with different requirements. 

Cheers

**Comment by v1v** [comment]
@andrewvc and @paulb-elastic , any feedback?

**Comment by vigneshshanmugam** [comment]
> For the very first release I'd like to be involved, though @vigneshshanmugam is already aware of the process since it's similar to the apm-agent-rum-js one. When do you plan to do a release?

Sure, will poke you when we are doing the release. But I am actually hoping to do a manual release for beta, but we can do an alpha just to test out the flow. 

Think we can close this issue as we already have a way to publish the package. Changelog automation can be done separately.
