### ISSUE TITLE
Journey is logging too many stderr

### ISSUE THREAD

**Issue by shahzad31** [elastic/synthetics#222]
While checking data on edge observability cluster, it has been noted that for many journeys there are 500 stderr docuements.

There seems like general playwright logs, i think these must also be contributing too why we have so much es traffic and data

`"2021-02-15T11:52:11.699Z pw:api   element is visible and does not move"
`
![image](https://user-images.githubusercontent.com/3505601/107943981-c3bdcd80-6f8d-11eb-9a99-930840de26c8.png)

query example

![image](https://user-images.githubusercontent.com/3505601/107944571-9de4f880-6f8e-11eb-816a-0f9b25a756bd.png)

**Comment by vigneshshanmugam** [comment]
The issue is edge environment is running with `DEBUG=pw:api*` flag enabled which is why we are seeing huge amounts of playwright logs. 

https://github.com/elastic/observability-test-environments/blob/d2554b3bd6c8b22a843e51b17ba9b9b28e7b62cf/ansible/roles/k8s-beats/templates/k8s/beats/heartbeat/heartbeat-deployment-us.yaml.j2#L39

@v1v Can we revert that change? We should be fine with removing it now as increasing memory helped solve the screenshot issue.

**Comment by v1v** [comment]
Heads up, 

`debug` configuration has been reverted and deployed in the edge environment
