### ISSUE TITLE
Running --inline inside of a directory with synthetics.config.ts breaks

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#407]
Spotted by @awahab07  catting a `--inline` script while the `$CWD` was https://github.com/elastic/synthetics-demo/tree/main/todos/synthetics-tests

```
abdul.zahid@Abduls-MacBook-Pro synthetics-tests % cat ../../../beats/x-pack/heartbeat/monitors/test-script.js | elastic-synthetics --inline
Error: Unable to read synthetics config: /Users/abdul.zahid/Desktop/Development/synthetics-demo/todos/synthetics.config.ts
    at readAndParseConfig (/Users/abdul.zahid/.nvm/versions/node/v14.17.0/lib/node_modules/@elastic/synthetics/dist/config.js:74:15)
    at Object.readConfig (/Users/abdul.zahid/.nvm/versions/node/v14.17.0/lib/node_modules/@elastic/synthetics/dist/config.js:47:34)
    at /Users/abdul.zahid/.nvm/versions/node/v14.17.0/lib/node_modules/@elastic/synthetics/dist/cli.js:179:29
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

AC:
* Stop reading the `synthetics.config.ts` when using inline monitors

**Comment by lucasfcosta** [comment]
After having investigated this problem, I'd like to confirm that the acceptance criteria remains the same, as I believe that the root cause of this bug could have been misleading.

Furthermore, I'd like to propose an extension and update to the AC in this issue:
* Users should be able to run `.ts` journeys using the `--inline` parameter
* We should stop reading `synthetics.config.ts` _unless_ users pass a `--config` parameter

To understand why I'm proposing this, read the sections below. In them, I explain the bug's root cause, which then helps making the case for the extension of this AC.

## Why does this bug happen?

This bug happens because when running the `@elastic/synthetics` executable, we're running it with `node`. That means whenever you type `npx @elastic/synthetics` you will kick-off a node process which will run the built [`cli.js`](https://github.com/elastic/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/src/cli.ts) in `dist`, which is [the module's entry-point](https://github.com/elastic/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/package.json#L21).

Given you're running built JS files within `node`, it will not be capable of processing `.ts` files, as is [the case of the `synthetics-demo` configuration](https://github.com/elastic/synthetics-demo/blob/6fc9ae3388b1054e6ff795c500544c496e4782ee/todos/synthetics.config.ts).

You can verify that this is the bug's root cause by building the module (`npm run build`) and adding a `console.log` to the line which catches the error thrown when requiring a configuration file.

```js
// dist/config.js
// ...
function readAndParseConfig(configPath) {
  try {
    /* eslint-disable @typescript-eslint/no-var-requires */
    const requiredModule = require(configPath);
    return interopRequireDefault(requiredModule).default;
  } catch (e) {
    console.log(e);
    throw new Error('Unable to read synthetics config: ' + configPath);
  }
}
// ...
```

After adding this line, running the built file with any inline journeys will result in:

```
$ cat ~/Repositories/synthetics/test/example.js | node ~/Repositories/synthetics/dist/cli.js --inline

export default (env) => {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at readAndParseConfig (/Users/lucasfcosta/Repositories/synthetics/dist/config.js:69:28)
    at Object.readConfig (/Users/lucasfcosta/Repositories/synthetics/dist/config.js:46:30)
Error: Unable to read synthetics config: /Users/lucasfcosta/Repositories/synthetics-demo/todos/synthetics.config.ts
    at readAndParseConfig (/Users/lucasfcosta/Repositories/synthetics/dist/config.js:73:11)
    at Object.readConfig (/Users/lucasfcosta/Repositories/synthetics/dist/config.js:46:30)
    at /Users/lucasfcosta/Repositories/synthetics/dist/cli.js:216:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Now, **the same bug does not happen if you're running the exact same journey, with the exact same arguments using `ts-node` to run the "unbuilt" file**.

```
cat ~/Repositories/synthetics/test/test.js | ts-node ~/Repositories/synthetics/src/cli.ts --inline
```

The error doesn't happen because `ts-node` is capable of parsing the `.ts` config file. If you use `ts-node` to run the built `dist/cli.js` file the bug also does not happen.

**Therefore, we conclude that the bug is _not_ caused by the config file itself, not being able to find it, or it being invalid TypeScript**. **This bug happens because `node` can't execute valid `.ts` config files**.

We can't read these `.ts` configuration files because `ts-node` is only registered ([allowing it to transpile required files](https://github.com/TypeStrong/ts-node#programmatic)) when not using the `inline` option, as you can see below.

https://github.com/elastic/synthetics/blob/5ddb5c281276ef70084269f767a6002c6040dafa/src/cli.ts#L129-L168

Furthermore, given that `ts-node` is only registered for journeys that are not inline it means that **users cannot run `.ts` journeys using the `--inline` parameter**, even though they could run those journeys just fine _without_ that parameter.


## Proposed extension and update to the AC

First, I believe that users should be able to run `.ts` journeys using the `--inline` parameter, for the sake of having a symmetric API (and by following the least-surprise principle). Furthermore, I'd simply consider not being able to run `.ts` files inline (or read `.ts` configs) a bug in itself.

Second, as a user, even though I'm running inline scripts, I could want to run those scripts using a particular config file, so that I can quickly test my journeys using the same parameters as I'll use on my whole suite later. I assume that supporting this scenario would be especially useful for folks who rely on [`playwrightOptions`](https://www.elastic.co/guide/en/observability/current/synthetics-configuration.html#synthetics-config-file). Given we do have a `--config` option, that option should be allowed when running `--inline` journeys.

**Comment by lucasfcosta** [comment]
Moved to "done done" as it's just a fix and has been released alongside the fix for it not to hang within Ubuntu images.
