### ISSUE TITLE
[Discussion] Renaming `journey` to `monitor`?

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#449]
One thing that comes up from time to time, and as recently as today in a conversation with @kyungeunni is confusion over the term `journey` in relationship to uptime monitors. It's confusing in that they are basically the same thing with two names depending on context.

This issue proposes we deprecate the use of `journey` in favor of a new name to align with the Uptime app. I propose either `monitor` (which aligns with the current Uptime naming) or `check`. Either way this issue proposes we find one word that works across Heartbeat, Uptime, Kibana and the synthetics agent.

## Why we originally named it `journey`

We originally chose the term `journey` to indicate that this was just a description of a path through a website, but not necessarily tied to a monitoring application. This naming fits better with the treatment of `@elastic/synthetics` as a general testing tool that happens to work well with the Elastic stack. The problem here is that it's a barrier to understanding how the two pieces fit together. 

It seems to me that there's a tension between:
1. A more agnostic name `journey`
2. A name that more clearly conveys the relationship between the two apps.

## Arguments in favor of `monitor`

1. Heartbeat and Uptime already use this terminology
2. It makes perfect sense for the monitoring use case
3. The only change that needs to occur is aliasing `journey` to `monitor` here, (and maybe handling either in the JSON sent to heartbeat).

## Arguments in favor of `check`

1. It's clear, and more generic than `monitor`, letting `@elastic/synthetics` as a laptop / CI only tool still potentially work

## My POV

IMHO it makes more sense to go with `monitor` given the large amount of labor required otherwise. Additionally, having a more focused use case is OK.

**Comment by paulb-elastic** [comment]
Thanks for raising this Andrew, it’s a good point that we’ve been using `monitor` and `journey` interchangeably, and now would be the time to make the change if we’re going to do it.

From your description, from a user’s perspective, it would just be about changing our DSL declaration of `journey()`?  There would be no other user facing change (as you say, in the UI, everything refers to **Monitor** in traditional Uptime as well as in Monitor Management).

There is a bit of _recursion_ (conceptually) in that a monitor may be declared in the UI, or the yml (under `heartbeat.monitors`), which is for a suite of more monitors (instead of _journeys_), but I think this makes sense, as these all end up as monitor results in Uptime.

I think it’s a good idea.

In terms of `check` or `monitor`, I personally prefer the term `monitor` as it fits with everything else we have (within our monitoring solution).  That said, I don’t have a problem with `check` if the collective thinks that’s a better option.

I think the capability to _run locally_ is ok if it’s called `monitor` rather than `check`.  From our product perspective, I see this as an additional capability of the product, as opposed it’s primary function (i.e. I don’t think there’ll be many use cases where people only use it locally for functional testing / CI, with no intention of using it in an Elastic stack somewhere).  If we’re _worried_ about that, we could potentially have an alias for `check` that is the same as `monitor` but I don’t think it’s worth the complexity or confusion it could cause users (and means we can’t use `check` for something else we may want in the future).

Curious to hear other people’s thoughts too.

**Comment by lucasfcosta** [comment]
I think that the term `journey` has its place, but indeed not in Kibana, as that's confusing. In my mind, a "journey" and a "monitor" have always been different concepts.

* **A journey** is a piece of code which can be executed by a monitor, by a CI pipeline task, or by users in their own machines. In other words **a journey defines a browser monitor's behaviour**.
* **A monitor** is a class of entities in Kibana which may have a status, and which can contain runs (checkgroups). **A monitor's behaviour may be defined by a "journey" if it's a "browser" type monitor**. Other monitors, like HTTP, don't have journeys associated to them.

See the diagram below for my understanding of the entities involved in the synthetics space (ignore the term "suites").

![Screenshot 2022-02-03 at 10 52 28](https://user-images.githubusercontent.com/6868147/152329046-b26caedd-d626-4600-b264-50d6708498f2.png)

Furthermore, I think the distinction between `journey` and `monitor` is important because a monitor may be the same, but its underlying journey may change, for example.

Considering the above, I'd probably not change the DSL to use the term `journey`, instead, I'd rename Kibana according to the above concepts. The only thing I'd change is that I'd highlight the difference between these concepts in our docs, and maybe have the "id" property changed to "monitor-id" to highlight the fact that a journey relates to a monitor, but they're not the same thing.

PS: As you can see on the diagram, on top of these, I've also thought of a  **a "suite" or "monitor configuration"** which creates one or more "monitors" in Kibana. A monitor configuration with a ZipUrl creates multiple monitors, while an inline script creates one, for example.

**Comment by vigneshshanmugam** [comment]
Closing this as we have agreed on some of these concepts in #470
