### ISSUE TITLE
New `push` command to sync with monitor management

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#470]
# Summary & ACs

1. There should be a `push` command in the `synthetics` agent which sends requests to Kibana to save a new monitor for each journey it found.
2. It should be possible to filter journeys to push in the same way we filter journeys to run
3. It should be possible to connect to the user's stack using CLI options, `config.ts` options, or environment variables (in this order of precedence).

> ⚠️ This issue covers exclusively the `synthetics` package changes: the CLI interface, filtering, bundling, compressing, and sending requests to Kibana.

### The push process

The monitor push process should bundle all the necessary files to run the journey, compress the bundle, and push the `zip` to Kibana using `base64` encoding.

> ⚠️ For now we won't worry with source maps or minification.

> ⚠️ Downloading, decoding and using this zip is covered in a separate Heartbeat issue.

### Connection options

Connection info for the user's stack can be specified via any of the options below, listed in order of precedence.

1. CLI options
2. `config.ts` options
3. Environment variables

> 👉  The new options would use either dashes for the cli version (e.g. `--kibana-space`), object notion for config.ts (e.g. `kibana.space`) and caps / underscores for env vars (e.g. `KIBANA_SPACE`).

The options are enumerated below in dot notation:

1. `cloud.id` `cloud.auth`  OR `kibana.url` / `kibana.username` / `kibana.password` : These let the user specify how to connect to the relevant kibana instance. In practice we only expect the `cloud.*` options to be used, but the `kibana.*` ones are useful for local development. For a description of parsing `cloud.id` for kibana info see [this file](https://github.com/elastic/logstash/blob/main/logstash-core/src/main/java/org/logstash/util/CloudSettingId.java#L28)
2. `kibana.space`: the kibana space to push the monitor to
3. `suite.id` / `suite.name` :  The id and name of this suite. If only the name is specified that is used as the ID

### Additonal fields sent to kibana

This should be able to use the current monitor creation APIs most likely with some minor changes. We would want to serialize the following additional fields for future use if we need to move / migrate data:

- `suite.id`
- `suite.name`
- `journey.name`
- `journey.id`

We have two choices in terms of handling the `monitor.id` and `monitor.name` values. For the name, we should concatenate `${journey.name} - ${suite.name}`, as we do today. For the `id` fields we should do the same with `${journey.id} - ${suite.id}` concatenated. Monitor management today uses an auto-generated UUID which is mandatory for saved objects with encrypted fields, but it makes more sense to override this when sending the monitor to heartbeat. We could use that UUID + queries across the new fields mentioned previously, but hewing to the old pattern means users can keep data.

#### Required fields

It will be possible to upload incomplete monitor configurations, for which the API will return a warning that is in turn shown on the CLI.

> ❓  Whether this can only be fixed in the CLI or on the UI as well is an open question we'll need feedback from @drewpost on. For now, let's make these configurations read-only on the UI and simply display warnings with them.

We should validate all required fields at the API layer, with the CLI client returning any errors to the console as warnings. These will not halt progress.

## Deletion
Deletion will not happen by default, but will be available through an optional parameter `--delete`.

By default, Kibana will return a list of monitors for the current suite that were not included in the latest push. The Synthetics agent can then use this information to inform the user that they can opt either to A.) Delete the monitors manually via the Synthetics app, or B.) Add `--delete` to the push command for automatic deletion

When `--delete` is specified, Kibana will search through the existing monitors for the suite within the specified space. If an existing monitor is not found in the list of monitors pushed, Kibana will delete the monitor and return a list of deleted monitors.

## Monitor Saved Object Id and Heartbeat ID
Although push monitors must use a uuid for their monitor saved object id, we will pass a custom id to heartbeat for push monitors. This id pattern will be `${journey.id}-${suite.id}`, as stated above in the Monitor Reconciliation section. 

This ensures:
1. That when a user attempts to search for the monitor in Uptime, they can find their monitors by their specified ids, instead of the monitor uuid.
2. In the event of accidental monitor deletion, history can be tied back to the original monitors, as new monitors will still use the `${journey.id}-${suite.id}` pattern when pushing to the service, tying the history back appropriately.

**Comment by dominiqueclarke** [comment]
Changes needed to the Add Monitor API
---
1. **Supplementing monitor config with defaults**: The client-side defines a set of default fields for each monitor type. This ensures that each monitor is always created with a minimum set of fields necessary to render the UI appropriately when navigating to the edit flow. Within the add monitor route, we should supplement the provided object with defaults before saving to saved objects, to ensure that clients outside of Kibana do not need to provide more fields than necessary and have context of what the defaults are supposed to be.

**Comment by lucasfcosta** [comment]
@dominiqueclarke indeed we're still pending a decision on what's the API to define the "monitor source" configurations from a correlated journey, as described in https://github.com/elastic/synthetics/issues/451.

I do think it would make sense to make the configuration be read-only from the UI monitor management view. In the future that could also be useful for us to push journeys from the recorder (which by the way should be even easier if we reduce the number of fields we need to push).

Also, just to confirm, if you're going to push using `sync`, that would simply bundle the JS and upload it, making it almost like a "zip url" monitor source, correct? Then the individual journeys contained in the code you've synced would appear in the Uptime app just as they do now.

That's what I understood from the comment I've added to the spec doc, but thought it would be worth confirming.

**Comment by andrewvc** [comment]
@dominiqueclarke I like the idea of default options provided by the API

@lucasfcosta I think that this issue is definitely pressing us to make progress on https://github.com/elastic/synthetics/issues/451 faster. I'm in favor of a minimal addition of the new `monitor` object passed into `journey` that can have any settings applied to it. @paulb-elastic the network options would be treated similarly to any other options.

@lucasfcosta WRT this being like a `zip_url` monitor, I'd say it's sort of like a hybrid `zip_url` and `inline`. The monitor saved object contains the full source, but that may be multiple files created by webpack or similar. There wouldn't be an extra asset to download.

**Comment by dominiqueclarke** [comment]
@andrewvc With the idea of a hybrid `zip_url`/`inline` monitor, have we thought about how we're passing these files to heartbeat? 

Also with regards to the idea of a hybrid, have we considered what the UX should be for displaying the monitor details with the edit monitor page? Seems like neither of the options we have currently, ZIP URL or inline, provide a sufficient UX.

**Comment by vigneshshanmugam** [comment]
>  WRT this being like a zip_url monitor, I'd say it's sort of like a hybrid zip_url and inline. The monitor saved object contains the full source, but that may be multiple files created by webpack or similar. There wouldn't be an extra asset to download.

I would like us to investigate this option a bit and come up with a solid plan before even starting the implementation, There are tons of ways to do this and we need to figure out the best way that gives the DX that would come closely to debug an error like its sitting on a local file system. Is anyone interested in working on this? If not, I am happy to take the lead and come up with an approach.

**Comment by lucasfcosta** [comment]
@andrewvc agreed, we do need to find a way to define these settings within the journey more quickly, which hopefully we'll be able to do in the breakout session today.

My suggestion is that:
* We add the API to allow for those throttling settings to be defined within the `journey` itself. I'm not concerned about a particular implementation here, just that it needs to be scoped to the `journey` level. We can define that in our breakout session later today.
* We also allow users to set defaults on their `synthetics` configuration files. Those defaults would be applied to all journeys we're uploading which do not have limits defined.

With regards to this monitor being a combination of `zip_url` and `inline`, I agree with @vigneshshanmugam that we would probably need to investigate this option a bit more. Although we'd not have an extra asset to download, we'd have to be sure the DX for debugging these (having access to sourcemaps/running them locally) is good. Also, it would be good to ensure we're not duplicating the full source per journey, but instead deriving journeys from one source (premature optimisation probably, but just thought I'd mention it).

**Comment by andrewvc** [comment]
@dominiqueclarke it's a good question WRT heartbeat serialization, and I've left that question unanswered because I'd like us to decide on one of the two approaches listed above: either a single combined file with source map (which could be inline) or a zip file. Once we know that we can tackle the heartbeat side.

@lucasfcosta good point about scoping throttling to the journey level, you're right it should apply locally too. Also, good point about the defaults in their synthetics configuration files. 

@lucasfcosta WRT asset serialization and duplication I'd agree it's a premature optimization and like us to avoid it unless there's an unforeseen insurmountable issue? Serializing into the monitor config aligns well with how fleet and the service work today and minimizes risk. Can you share your DX concern? Remember, the runner reports the source separately in the result documents sent to the cluster, after having unpacked these etc. Also, users would have a local copy as well (or one in a git repo etc.)

**Comment by lucasfcosta** [comment]
Hi all, we've had a breakout earlier today about how the `push` command will interfere with the network settings and how should the DSL interface with pushes. There are some relevant notes [here](https://github.com/elastic/synthetics/issues/451#issuecomment-1069305122) which would be useful for everyone to read.

We've also decided that, with regards to the push command:
* We’ll schedule a separate breakout including @shahzad31 and @dominiqueclarke 
* The most important thing to get done as soon as possible is figuring out what changes we need to Kibana
    * We can release synthetics-agent changes later
* In terms of the breakout:
  * Lucas will investigate Kibana APIs for sync
  * Vignesh and Emilio will split the Agent part into
      * Webpack + source code generation
      * Push command itself + API call

**Comment by lucasfcosta** [comment]
# DSL & Uploads + Perf Problems

* We’re happy to go with `monitor.use` and monitor being an arg passed to the journey
* We don’t have to invoke the steps callback
* This is subject to the challenges we’ll find on the Push spike but we'll try to stick to our decisions when possible
* The service will push all the same source code for all monitors. We’ll do this because that’s the closest to the functionality we already have.
    * There will be duplication for each monitor
    * There will be one monitor per journey but all of them have all source
    * We’ll define which journey that particular monitor will run using our filtering functions
* There could be a performance problem if the journey uploaded is too big because we’d have to decrypt it to be able to sync it to the service
    * For now, we’re okay with with this performance degradation
    * There are multiple avenues to solve this problem later
        * A separate breakout for this will be scheduled once we’ve quantified the problem
* Optimisation problems for syncing source with the service/heartbeat
    * Source-maps are huge, how do we deal with that?
    * When pushing files what we’ll do (initially) will be:
        * Creating a zip with the minimal number of files necessary
        * Upload that to Kibana
        * Kibana would then sync that with the service (using a base64 string which will get written to a `ConfigMap`)
* **[ACTION]** @lucasfcosta We’ll need a separate breakout on this topic


# Kibana API changes

* Summarised in: https://github.com/elastic/kibana/issues/127677
* Prevent editing of push monitors ✅ 
* Adding a "is managed" or "is push" monitor boolean to the SyntheticsMonitor type ✅ 
    * Is this the best name for this flag? ➡️  `isPush`
* Supplementing defaults for Monitor Saved Objects ⚠️ 
    * We’ll do this on the API route which _receives_ then, not on the _push_ side.
* Adjusting types for the add monitor API ✅ 
    * We’ll eliminate the need to pass all of a location’s information
    * We’ll pass only a location ID and a flag indicating whether this was pushed
        * Synthetics client will make a call to Kibana to list locations
            * API key will be needed anyway for the push
        * IDs will _not_ prevent uploads from being done, but we’ll show a warning
        * Depending on time pressures we’ll allow users to edit locations in the UI (initially we don’t need to)
* Encrypting the monitor source ✅ 
    * We’ll have to figure out a field name that’s not source.inline_script so that we can add that to the list of fields which will be encrypted
        * That’s considering the zip upload discussed for optimisation reasons
* Bulk API ✅
    * **We’re fine with doing multiple requests for now**, although it’s an excellent idea

# API Keys (in the scope of Sync)

* For an MVP we can advise people to create a new user with basicauth enabled + reduced permissions and use that to push monitors
    * Using API keys would require permissions for others to create API keys and it could expand the permission set there
* If users try to push monitors before the API key for indexing results back to ES does not exist we’ll throw an error
    * Security team is aware of the feature here ➡️  https://github.com/elastic/kibana/issues/127978
    * We would need to engage with them to be able to get API keys with a reduced scope than the user who’s creating it
* If users use complicated auth flows/2FA it would complicate the authentication from the agent, so **in the future** we should go for API keys (once we have the necessary support.
* **[ACTION]** @dominiqueclarke to schedule a meeting with the security team to clarify it further

**Comment by dominiqueclarke** [comment]
05/03/22 Meeting Update
--
cc: @andrewvc @paulb-elastic @vigneshshanmugam Please let me know if I missed anything

## Suite Id
Suite id will be required, but the exact mechanism for how it's generated is up for further debate

### TBD
* Auto generating suite id vs user-specified suite id

## Deletion
Deletion will not happen by default, but will be available through an optional parameter `--delete`.

By default, Kibana will return a list of monitors for the current suite that were not included in the latest push. The Synthetics agent can then use this information to inform the user that they can opt either to A.) Delete the monitors manually via the Synthetics app, or B.) Add `--delete` to the push command for automatic deletion

When `--delete` is specified, Kibana will return a list of deleted monitors

## Monitor Saved Object Id and Heartbeat ID
Although push monitors must use a uuid for their monitor saved object id, we will pass a custom id to heartbeat for push monitors. This id pattern will be `${journey.id}-${suite.id}`

This ensures:
1. That when a user attempts to search for the monitor in Uptime, they can find their monitors by their specified ids, instead of the monitor uuid.
2. In the event of accidental monitor deletion, history can be tied back to the original monitors, as new monitors will still use the `${journey.id}-${suite.id}` pattern when pushing to the service, tying the history back appropriately.

## User Interviews
A desire for user interviews came out of the meeting, specifically surrounding the question of whether users expect monitors to auto-delete when using a git-based or push workflow, or if they would prefer alternative delete workflows. We would like to reach out ideally to external customers, but also to some of our internal users, such as Stephanie Jackson, the robots team, cloud SREs, or infra.

**Comment by vigneshshanmugam** [comment]
Released in v1.0.0-beta.26
