### ISSUE TITLE
Disappearing tests in Uptime/Monitors

### ISSUE THREAD

**Issue by StuGray86** [elastic/synthetics#500]
Just wondering if anyone can explain the logic of when tests show in the monitors list?

Often I'll upload a new test it will run once, and appear in the monitors list, but will then never show again. It doesn't matter if the test succeeds or fails. 

These tests continue to run in Discover, but never appear again under monitors.

You can drill down to these tests within 'pings over time' though. 

Seems like a bug to me?

**Comment by vigneshshanmugam** [comment]
We had some bugs around missing Summary documents that was on older versions of HB, but I would like to check some details with you before coming to a conclusion. 

1. Elastic stack version
2. HB version and Synthetics version you are running.
3. An example monitor that can reproduce the same error. 

Thanks.

**Comment by StuGray86** [comment]
Hi.

1. Elastic stack version: 8.1.3
2. HB: `docker.elastic.co/beats/heartbeat:7.16.3` and Synth: `@elastic/synthetics@1.0.0-beta.25`
3. None of the tests are that complex. Some are just as basic as hitting a URL

Thanks

**Comment by vigneshshanmugam** [comment]
Would it be possible for you to upgrade the HB to 8.x and give it a try? We had some bugs in the agent that was not emitting all the required events for the monitor to be completed. Issue details - https://github.com/elastic/sdh-kibana/issues/2659

**Comment by StuGray86** [comment]
Seems to be working now. Thanks for your help

**Comment by sarahnani** [comment]
@StuGray86 I had the same problem here, did updating HB to 8.x work for you? This is my problem: https://github.com/elastic/kibana/issues/176431

@vigneshshanmugam the link is broken, can you find the right link?

**Comment by vigneshshanmugam** [comment]
@sarahnani We have come a long way since and this issue has been fixed in the newer versions of Heartbeat, I think the best path forward would be to update to the last version of Heartbeat and the Synthetics agent. 

We also have a dedicated Synthetics app - https://www.elastic.co/guide/en/observability/current/monitor-uptime-synthetics.html where you can have GitOps based overview as opposed to using `heartbeat.yml`, You could still run them on private VM's using [private locations](https://www.elastic.co/guide/en/observability/current/synthetics-private-location.html).
