### ISSUE TITLE
Chore: Remove hotfix (coincide with 8.5 release)

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/synthetics#606]
Relates to https://github.com/elastic/synthetics-dev/issues/136

To account for project monitor streaming issues in < 8.4.1, a hotfix was added to the synthetics-agent to push each monitor as an individual request.

Now in 8.5, enhancements have been in progress to improve the performance on project monitors. Once 8.5 ships, we should consider removing the hotfix to take advantage of the performance improvements.

The hotfix should not be removed until all of the following are true in a release

- [x] Monitors are now created in bulk in 8.5(Related: https://github.com/elastic/kibana/pull/140781
- [x] Monitors are now able to be edited in bulk in 8.5 (Related: https://github.com/elastic/kibana/pull/140990)
- [x] Monitors are now able to be deleted in bulk (Related: https://github.com/elastic/kibana/pull/140781)

**Comment by vigneshshanmugam** [comment]
We will do this post the 8.5 Release to ensure the 
- The next released version of Synthetics sends the batched request instead of creating single request for each monitors. 
- Using these new versions with private locations might still end up with timeouts, but with users wanting to use lightweight monitors, they will naturally upgrade the stack and the agent, so the breakage point is pretty minimal.

**Comment by paulb-elastic** [comment]
We're not going to do this, as we'll be changing the implementation in https://github.com/elastic/kibana/issues/142418
