### ISSUE TITLE
Shared synthetic monitor locations are not functional

### ISSUE THREAD

**Issue by Chillwind132** [elastic/synthetics#618]
Hi Team,

We were able to successfully run a number of simple synthetic monitors on our private location utilizing the "project monitors" feature. Unfortunately, it seems that public locations such as "North America - US East" and "North America - US West" are not functional. We tried configuring monitors via the uptime app in Kibana as well as pushing them via the project monitors but none of the options worked and we were not able to run any synthetics checks on the referenced shared locations. 

We can only see test results for our private location, looks like public locations are not functional. Please refer to the attached screenshots.

Can you please help us resolve this issue? 

Thank you,
Mike

![Screenshot 2022-10-03 170840](https://user-images.githubusercontent.com/99220831/193684641-2e873820-6b62-4d16-b2e1-3595ba9a8bca.png)
![Screenshot 2022-10-03 171738](https://user-images.githubusercontent.com/99220831/193684656-48b2fa24-8199-4eb6-a8e4-987971f5f2f2.png)

**Comment by paulb-elastic** [comment]
Sorry to hear you’re having problems @Chillwind132.

Do you know if your Kibana instance has internet access (that doesn’t require any kind of proxy auth)?  When tests are configured to run from public locations, your Kibana instance needs to be able to connect out to the testing service.

**Comment by paulb-elastic** [comment]
@Chillwind132, also, you mentioned that this didn’t work when adding a monitor from the UI either.  Can you do this again please, but try the _“Run test”_ button at the bottom of the page once you have added a configuration for the monitor, to run on 1 location?

Use a simple inline script for this, something like:
```
step("Elastic Homepage", async () => {
  await page.goto('https://elastic.co');
});
```
(you don’t need to save this as a monitor, it’s just to see if it works)

Does this progress any further?  Do you get any errors from this?

**Comment by Chillwind132** [comment]
Hi @paulb-elastic - when we run the referenced inline script on NA - US East it goes into infinite "Pending" state. No progress and no errors. Please refer to the attached screenshot.

I am not sure about the internet access for our Kibana instance, but I know that we deployed it through a relatively straightforward process in elastic cloud. The only change that we made in kibana was saml, everything else is untouched.

Regards,
Mike

![image](https://user-images.githubusercontent.com/99220831/193900053-9814b8ec-8af4-4616-adcd-5df5c39c097b.png)

**Comment by maneta** [comment]
Hi @Chillwind132, I've found the client deployment in ESS:
 * Deployment URL: https://admin.found.no/deployments/f271f3350d6146bcab32ffe924f4cc36 
 * Elastic Search Cluster ID: `b53bd737ff2c4d4ead537688079d0d33`
 
Please let me know if this is the wrong deployment.

I've tried to generate a pair of Kibana ephemeral credentials(I can do that because I'm an Elastic Cloud Admin, and the admin portal has a feature to generate these credentials) to check how the client was configuring their Synthetics tests. For some reason, the credentials were not working for me. Which is weird and might imply that the client has some unusual configuration regarding the Kibana authentication system.

Checking the logs on our Synthetics clusters, I've found the following logs:

`Failed to connect to backoff(elasticsearch(https://b53bd737ff2c4d4ead537688079d0d33.northamerica-northeast1.gcp.elastic-cloud.com:443)): 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"API key: unable to find apikey with id nbMSFIMBJIKCAZiiJWRB","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate with provided credentials and anonymous access is not allowed for this request","additional_unsuccessful_credentials":"API key: unable to find apikey with id nbMSFIMBJIKCAZiiJWRB","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}`

The logs also indicate that the Synthetics service cannot re-ingest the results due to an Auth problem(401) since the API key they use is not found on the Deployment.

I think the client might have some special configuration regarding the Kibana Authorization that is overriding some ESS defaults, which is unauthorizing my ESS-generated ephemerals keys and the Synthetics API Key.  

Maybe would be good to review the SAML config with the client to check if that configuration is overriding something in the Kibana auth system.

**Comment by Chillwind132** [comment]
Hi Daniel,

Thank you for your email. This is good information and we will look into
it.

Regards,
Mike

**Comment by Chillwind132** [comment]
Danny from elastic support was very helpful in guiding us to a successful resolution. We are now able to run synthetic monitors on shared locations after re-generating our synthetics-api-key.

Thank you!
Mike
