### ISSUE TITLE
ts-node dependency is causing issues in Kibana and doesn't seem to be used

### ISSUE THREAD

**Issue by spalger** [elastic/synthetics#654]
ts-node is included in the "dependencies" for synthetics, but a quick search for uses of ts-node show no results, and I'm also suspicious that it is actually a production dependency. Can we remove it from synthetics?

**Comment by spalger** [comment]
Not sure why my initial search failed, but I've found it now. Is there a chance we can make this the responsibility of the test author? I'm also investigating why storybook is loading ts-node when it's installed, but I would love to be able to not have this relatively complex dependency installed if possible.

**Comment by vigneshshanmugam** [comment]
@spalger Apologies for the delay. The reason why ts-node is being used is kind of two fold

1. We need to have first class support for Synthetics tests in TypeScript and JavaScript along with the configuration files which can be in both formats. 
2. To accomplish step1, we chose ts-node instead of writing babel transformation step. 

We will probably move to `esbuild` sooner given we are heavily using it for bundling the journeys when pushing the project based monitors. 

Removing `ts-node` for now is not an easy option. Let us know if you have any suggestions.

**Comment by spalger** [comment]
esbuild is a pretty big dependency to add to Kibana (which has a dependency on synthetics), a babel transform is really trivial to write for TypeScript, is pure JS, and runs plenty fast if it's operating on less than a couple thousand files. I'd be happy to take care of it and eliminate this dependency without worrying about a new native dependency.

**Comment by vigneshshanmugam** [comment]
Agreed babel transform would be way easier to deal with. But we do already use some native deps like `esbuild` and `sharp` where the former is required for bundling the journeys to send it to Kibana monitor management and later for deduping screenshots in a much efficient way. Its hard to do both of those faster with JS deps. 

Let me know if there is any way we can help to avoid the issues in Kibana.

**Comment by vigneshshanmugam** [comment]
Good news, we are getting rid of `ts-node` - https://github.com/elastic/synthetics/pull/687, but unfortunately we cannot get rid of `esbuild` or `sharp` which are native deps. Will close this issue once the PR gets merged in, Please do let us know if we can help in some other way.

**Comment by spalger** [comment]
Sweet, thanks!
