### ISSUE TITLE
synthetics push command with lightweight monitors doesn't work for files other than heartbeat.yml

### ISSUE THREAD

**Issue by BenB196** [elastic/synthetics#705]
(Initially reported [here](https://discuss.elastic.co/t/synthetics-push-command-issues/325650?u=benb196)

I would like to be able to have a project structure like:

```
lightweight/
    ICMP.yml
    TCP.yml
    HTTP.yml
```

An example of the contents of `ICMP.yml`

```yaml
heartbeat.monitors:
  - type: icmp
    name: google.com
    id: google
    enabled: true
    hosts: ["google.com."]
    schedule: "@every 20s"
```

Then run a push command which only deploys a single file to a set of locations, using the `--pattern` option:

`npx @elastic/synthetics push --auth <token> --url <url> --id icmp --space default --private-locations 'ICMP' --pattern "lightweight/ICMP.yml"`

But when I run the above command, I get the following error:

```
C:\...\lightweight\ICMP.yml:1
heartbeat.monitors:
                  ^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Object.newLoader [as .js] (E:\GitHub\monitors\elastic-agents\synthetics\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at requireSuites (E:\GitHub\monitors\elastic-agents\synthetics\node_modules\@elastic\synthetics\src\loader.ts:123:5)

Node.js v17.0.1
```

Switching the file name from `ICMP.yml` to `heartbeat.yml` clears this error, but then breaks the desired project/file structure.

**Comment by vigneshshanmugam** [comment]
@BenB196 Thanks for the detailed issue. The problem here is the usage of `--pattern "lighweight/ICMP.yml"` and nothing to do with the folder structure in general. 

When the pattern is passed that way, Now synthetics runner will try to consider the files ending in that pattern as `Journey Files` which is supposted to be a `TypeScript or JavaScript` files and as a result throwing a Syntax error as its a yaml file instead. 

The push command effectively pushes everything on the current directory where it is run from, If you want to pick a monitor based on a folder path, then the folder structure has to be changed as we want it to resemble like `git push`. 

Please do let us know if you need more information. Thanks.

**Comment by BenB196** [comment]
Hi @vigneshshanmugam thanks for the information.

I adjusted the structure to look like

```
lightweight/
  ICMP/
    ICMP.yml
```

And the push command no longer errored out on parsing.

Based on your comment, maybe this is more of a documentation issue?

If you run:

`npx @elastic/synthetics --help`

It will output the line:

`--pattern <pattern>                RegExp file patterns to search inside directory`

There is no mention in there that the `--pattern` option is only intended to work for Journey Files, which I guess is where my confusion came from.

**Comment by vigneshshanmugam** [comment]
Yeah it works because, now it cant find any journeys with that pattern. 

You are right, the docs are indeed misleading here. The pattern is basically to match if the file structure for journeys if you have saved it other than `<filename>.journey.ts`. Check how we are using it here - https://github.com/elastic/synthetics/blob/46be5eb6cdbc549bd14f755dbadd8e852a7c33c2/src/loader.ts#L142

Will adjust the docs and CLI options accordingly. Thanks once again 👍🏽
