### ISSUE TITLE
Make tags behave consistently

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/synthetics#780]
There has been some confusion over the current implementation of tags because it differs from what is expected (for example as raised in https://github.com/elastic/synthetics/issues/775).

Synthetics needs to be updated to consolidate how `tags` (and `match` in the CLI) work, as follows:
- Remove `--tags` and `--match` from `push`
  - If either `--tags` or `--match` is used with `push`, fail the `push` with an error and print a message
    | push cannot be used with either '--tags' or '--match', see [link to forum post] for more on why we removed this broken behavior.
  - Add a deprecation notice to the release note including this change
  - Update the `push --help` text that currently suggests it will filter on `push`
  - Note that `--tags` and `--match` are still valid options for _running_ monitors (but not with `push`)
  - Update the [docs page](https://www.elastic.co/guide/en/observability/current/synthetics-command-reference.html) that `--tags` and `--match` are only relevant when running monitor (not pushing them)
- Tags defined for an **individual monitor**
  - Tags can continue to be defined for an individual monitor via:
    - `monitor.use.tags` of `journey({name:'My Monitor', tags:['foo']}, …`
      - Note that the `journey()` version is not documented or intended for general use (will maybe documented in the future if there's a need)
- Add `monitor.use.tags` support to the `synthetics.config.ts`
  - Precedence order is that this global setting is overridden by any monitor specific setting for `tags`
    - Either `monitor.use.tags` or `journey…` type of definition
  -  i.e. the behaviour is consistent with `locations`
- Tags defined against a monitor in any way are then reflected in the Synthetics UI monitor tags
- Add a sticky forum post for a month or so describing the change

**Comment by andrewvc** [comment]
Suggestion for the copy for the error on `--push` or `--match`

>  push cannot be used with either '--tags' or '--match', see <link to forum post> for more on why we removed this broken behavior.

Proposed forum post text.

> Why we're removing the `--tags` and `--match` flags from the Synthetics CLI
> 
> Our next release of Elastic Synthetics fixes a confusing and sometimes painful behavior when combining the `push`
> subcommand with the `--tags` and `--match` flags. Normally the `push` subcommand pushes all monitors.
> Some users have tried to push just a subset of monitors by running a command like `npx @elastic/synthetics push --tags mytag` and have been surprised that this will delete all monitors remotely that do not have that tag! We've decided
> to remove these flags because, to be frank, there was no good use for them that we could find in the context of `push`
>  that wouldn't be mostly confusing and dangerous.
>
> Note that these flags will continue to work where they are genuinely useful, when running tests locally, so please continue
> running commands like `npx @elastic/synthetics --tags mytag mydir`, but just be aware that using them elsewhere will
> generate an error message. 
>
> Some readers may be asking themselves then, how do you push only a subset of monitors? There are a few answers to that.
> First, users should be aware that the push command only pushes changed monitors in the first place. Second, if you're
> using tags to split a project up so multiple groups can work independently, consider either using two projects and/or making sure that only the whole project is ever pushed, and then only via a CI job after a PR merge.
>
> Questions? Feedback? Please let us know in the comments below.

**Comment by angeliski** [comment]
Hi @paulb-elastic and @vigneshshanmugam 

How can I push just some journeys now?

The behavior to be able to push just journeys based in tag/match is really useful, we used that in heartbeat 7.15, but now is gone.

Is there any way to achieve that?

**Comment by vigneshshanmugam** [comment]
> How can I push just some journeys now?

@angeliski Since we have moved away from supporting tags/match on the push command. Our recommendation is to structure the journeys that are distinct in their individual projects and only push them. An example would be a mono-repo of synthetic monitors with different projects underneath. 
```
synthetics-monitors
   -> project-a
       -> journeys 
       -> package.json
       -> synthetics.config.ts
   -> project-b
       -> journeys 
       -> package.json
       -> synthetics.config.ts

```

Please do let us know if you have any further questions.

**Comment by angeliski** [comment]
Hi @vigneshshanmugam 

That don't work for us because we have the same test in different projects.
Our current suite run the same test (like buy a product) for different plans, because our plans run in different infrastructure.

So in some cases we can have a fail test in the Gold plan, but everything ok in the Platinum plan.

I use a workaround with `--pattern` and the journey file's name, but would be really nice to use tags for that.

I didn't get why we can have that filter in push. Is there any problem to use the same behavior in both cases?

**Comment by vigneshshanmugam** [comment]
@angeliski Apologies for the delay, Since the tags filtering has been asked again externally a lot and also internally, we have decided to bring it back. Also now that we have a prompt to stop users from deleting monitors accidentally - https://github.com/elastic/synthetics/pull/912, we can safely bring the tags back. We will work on it and release it on the next version. Timeline would be less than a week. Thanks.
