### ISSUE TITLE
Show which monitors were deleted

### ISSUE THREAD

**Issue by henrikno** [elastic/synthetics#803]
It'd be helpful if there was a way to know which monitors were removed when pushing to verify that it didn't delete something it wasn't supposed to.

`| > Monitor Diff: Added(0) Updated(9) Removed(5) Unchanged(0)`

Perhaps using a verbose/debug mode?

I actually see a `--debug` flag in the docs
<img width="1097" alt="image" src="https://github.com/elastic/synthetics/assets/147660/d5a029ff-8b39-4d15-a532-842870ec9398">
https://www.elastic.co/guide/en/observability/current/synthetics-command-reference.html#elastic-synthetics-command

But when trying it I get 
```
npx @elastic/synthetics --debug
error: unknown option '--debug'

npx @elastic/synthetics -V
1.1.0
```

**Comment by paulb-elastic** [comment]
Thanks for raising @henrikno.  Agree, it seems that both `... --debug` and `... push --debug` are invalid.

Also, running `--help` on the CLI (or with `push --help`) doesn't give this as an option.

It looks like it's always been in the [docs](https://www.elastic.co/guide/en/observability/7.17/synthetics-command-reference.html) and may be an oversight.

@vigneshshanmugam do you know if there's ever been a `--debug` option in earlier versions? (cc @colleenmcginnis)

However, back to your original point, I think it's a great idea, being able to see what's been removed.  Having a _debug_ or _verbose_ might be a good idea.

However, I was also wondering if it would actually be useful always, e.g. always show even just the name, and/or id of what's been removed?  Mainly because if someone wanted to know, it's too late if they forgot to add the flag when they did the `push`.  It's rare that lots of monitors are going to be deleted where a user might be _annoyed_ that they were listed, but still useful whether that's interactive via CLI, or as part of a pipeline and in the logs.

What do others think - a useful default addition to output what's been deleted (and then maybe remove `--debug` from the docs)?

cc @elastic/uptime

**Comment by vigneshshanmugam** [comment]
> @vigneshshanmugam do you know if there's ever been a --debug option in earlier versions? (cc @colleenmcginnis)

`--debug` has been removed even during the beta. In favor of `DEBUG=synthetics` environment variable. Didnt know we had been using it on the docs page. Will open a PR to get rid of that. 

++ to the idea here to show the deleted monitors when the debug logs are enabled.

**Comment by gsantoro** [comment]
I think having a `-debug` option would also be great for any changes in the journeys/monitors. Meaning not just for `Removed` but also for `Added`, `Updated`, and `Unchanged`

Given that journeys/monitors are identified by monitor_id = `<name>-<project-id>-<space>`, I believe that when pushing the journeys/monitors, we should:
1. output the project id. This is DONE now
2. output the space. this is missing
3. if `--debug` is enabled, we should display the name of all the changes journeys/monitors. Using the local name instead of the entire monitor_id would make it more readable. Using the full monitor_id would be ok as well.

**Comment by vigneshshanmugam** [comment]
Space is already fixed in this PR - https://github.com/elastic/synthetics/pull/908, Otherwise will come as a followup.
