### ISSUE TITLE
Expose journey/step info details on the hooks

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/synthetics#954]
+ Use case is to run specific logic based on the status of the journey (whether its failed or succeeded).

**Comment by mduarte** [comment]
Example use case:
We combine methods that create a serverless project, with methods that do different types of validations into several journeys. When calling the method that creates the serverless project we also include an `after` step that cleans up the project that will be created in the step "create project". This way the different journey writers don't need to worry about including a step to cleanup because it is returned as part of the list of steps to create a project.
The thing is, ideally we would not be deleting the project if the some other step of the journey fails (the journey fails some validation). To do this ideally we would be able to access some information about the journey to know if it succeeded or failed before performing the cleanup step.
